theme: jekyll-theme-slate
name: privca - Minimalist private CA and server/client cert tool
description: Enable two-way authentication within a closed group.<br> 
Includes walk-through of example application to lighttpd 1.4.45 as server, Firefox v65.0 browser as client.
